export { default as Navbar } from "@/component/Navbar" 
export { default as Footer } from "@/component/Footer"
export { default as HomepageProperties } from "@/component/HomepageProperties"
export { default as Infoboxes } from "@/component/Infoboxes"
export { default as PropertyCard } from "@/component/PropertyCard"
export { default as Hero } from "@/component/Hero"
export { default as InfoboxProperties } from "@/component/InfoboxProperties"
export { default as PropertyDetails }  from "@/component/PropertyDetails"
export { default as PropertyHeaderImage } from "@/component/PropertyHeaderImage"
export { default as PropertySidebar } from "@/component/PropertySidebar"
export { default as Spinner } from "@/component/Spinner"
export { default as LoginLeftPanel } from "@/component/LoginLeftPanel"
export { default as LoginRightPanel } from "@/component/LoginRightPanel"
export { default as SignupPage } from "@/component/SignupPage"
export { default as AddProperty } from "@/component/AddProperty";
export { default as PropertyRates } from "@/component/PropertyRates"
export { default as AddPropertyImage } from "@/component/AddPropertyImage"
// export { default as dashboard } from "@/dashboard/dashboard"